### ISSUE TITLE
Issue connecting to site

### ISSUE THREAD

**Issue by retryoos** [Eryck13/BrowserSpoof#2]
When i run the .exe I get an error that the site can not be found

**Comment by Eryck13** [comment]
Can you send the error its saying in console

**Comment by retryoos** [comment]
Wait I think I found the problem, I cant run local right, I need proxies to run?

**Comment by Eryck13** [comment]
Yes, currently you need proxies to run, ill be adding local support when I add Gmail support this weekend most likely.

**Comment by retryoos** [comment]
Okay sounds good
